// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title SalaryRangeVerifier
 * @notice Groth16 verifier for the salaryRange.circom circuit.
 *
 * This contract is generated by snarkjs from the compiled circuit + trusted setup.
 * The verification key constants (ALPHA, BETA, GAMMA, DELTA, IC) MUST be replaced
 * with values produced by the actual ceremony. See:
 *   packages/contracts/circuits/README.md
 *
 * Public signals layout (matches circuit `main {public [minSalary, maxSalary]}`):
 *   publicInputs[0] = minSalary
 *   publicInputs[1] = maxSalary
 *   publicInputs[2] = valid (must equal 1)
 *
 * @dev Called by the ATTESTA backend after receiving a proof from the candidate's browser.
 *      The backend calls verifyProof() and records the result on-chain. Only a boolean
 *      (pass/fail) is stored — the actual salary never appears on-chain.
 */
contract SalaryRangeVerifier {

    // ── Elliptic curve constants (BN128 / alt_bn128) ─────────────────────
    uint256 constant PRIME_Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    struct G1Point { uint256 X; uint256 Y; }
    struct G2Point { uint256[2] X; uint256[2] Y; }

    // ── Verification key ─────────────────────────────────────────────────
    // REPLACE THESE with values from: snarkjs zkey export verificationkey salary_range_final.zkey vk.json
    // Then re-run: snarkjs zkey export solidityverifier salary_range_final.zkey SalaryRangeVerifier.sol

    function verifyingKey() internal pure returns (
        G1Point memory alpha1,
        G2Point memory beta2,
        G2Point memory gamma2,
        G2Point memory delta2,
        G1Point[4] memory ic   // IC[0] + IC[1]*minSalary + IC[2]*maxSalary + IC[3]*valid
    ) {
        // ── PLACEHOLDER — replace after trusted setup ──────────────────
        alpha1 = G1Point(
            0x0000000000000000000000000000000000000000000000000000000000000001,
            0x0000000000000000000000000000000000000000000000000000000000000002
        );
        beta2 = G2Point(
            [uint256(0x0000000000000000000000000000000000000000000000000000000000000001),
             uint256(0x0000000000000000000000000000000000000000000000000000000000000002)],
            [uint256(0x0000000000000000000000000000000000000000000000000000000000000003),
             uint256(0x0000000000000000000000000000000000000000000000000000000000000004)]
        );
        gamma2 = G2Point(
            [uint256(0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2),
             uint256(0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed)],
            [uint256(0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b),
             uint256(0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa)]
        );
        delta2 = G2Point(
            [uint256(0x0000000000000000000000000000000000000000000000000000000000000001),
             uint256(0x0000000000000000000000000000000000000000000000000000000000000002)],
            [uint256(0x0000000000000000000000000000000000000000000000000000000000000003),
             uint256(0x0000000000000000000000000000000000000000000000000000000000000004)]
        );
        ic[0] = G1Point(
            0x0000000000000000000000000000000000000000000000000000000000000001,
            0x0000000000000000000000000000000000000000000000000000000000000002
        );
        ic[1] = G1Point(
            0x0000000000000000000000000000000000000000000000000000000000000003,
            0x0000000000000000000000000000000000000000000000000000000000000004
        );
        ic[2] = G1Point(
            0x0000000000000000000000000000000000000000000000000000000000000005,
            0x0000000000000000000000000000000000000000000000000000000000000006
        );
        ic[3] = G1Point(
            0x0000000000000000000000000000000000000000000000000000000000000007,
            0x0000000000000000000000000000000000000000000000000000000000000008
        );
    }

    // ── Elliptic curve operations ─────────────────────────────────────────

    function negate(G1Point memory p) internal pure returns (G1Point memory) {
        if (p.X == 0 && p.Y == 0) return G1Point(0, 0);
        return G1Point(p.X, PRIME_Q - (p.Y % PRIME_Q));
    }

    function addition(G1Point memory p1, G1Point memory p2) internal view returns (G1Point memory r) {
        uint256[4] memory input = [p1.X, p1.Y, p2.X, p2.Y];
        bool success;
        assembly {
            success := staticcall(sub(gas(), 2000), 6, input, 0x80, r, 0x40)
        }
        require(success, "ec-add-failed");
    }

    function scalar_mul(G1Point memory p, uint256 s) internal view returns (G1Point memory r) {
        uint256[3] memory input = [p.X, p.Y, s];
        bool success;
        assembly {
            success := staticcall(sub(gas(), 2000), 7, input, 0x60, r, 0x40)
        }
        require(success, "ec-mul-failed");
    }

    function pairing(
        G1Point memory a1, G2Point memory a2,
        G1Point memory b1, G2Point memory b2,
        G1Point memory c1, G2Point memory c2,
        G1Point memory d1, G2Point memory d2
    ) internal view returns (bool) {
        uint256[24] memory input = [
            a1.X, a1.Y, a2.X[0], a2.X[1], a2.Y[0], a2.Y[1],
            b1.X, b1.Y, b2.X[0], b2.X[1], b2.Y[0], b2.Y[1],
            c1.X, c1.Y, c2.X[0], c2.X[1], c2.Y[0], c2.Y[1],
            d1.X, d1.Y, d2.X[0], d2.X[1], d2.Y[0], d2.Y[1]
        ];
        uint256[1] memory out;
        bool success;
        assembly {
            success := staticcall(sub(gas(), 2000), 8, input, 0x300, out, 0x20)
        }
        require(success, "pairing-failed");
        return out[0] != 0;
    }

    // ── Public API ────────────────────────────────────────────────────────

    /**
     * @notice Verify a Groth16 proof for the salary range claim.
     * @param a  Proof component π_a (G1)
     * @param b  Proof component π_b (G2)
     * @param c  Proof component π_c (G1)
     * @param input Public signals: [minSalary, maxSalary, valid]
     * @return true if the proof is valid (candidate's salary is in [minSalary, maxSalary])
     */
    function verifyProof(
        uint256[2]    memory a,
        uint256[2][2] memory b,
        uint256[2]    memory c,
        uint256[3]    memory input
    ) public view returns (bool) {
        // valid signal must be 1
        require(input[2] == 1, "invalid-valid-signal");

        (
            G1Point memory alpha1,
            G2Point memory beta2,
            G2Point memory gamma2,
            G2Point memory delta2,
            G1Point[4] memory ic
        ) = verifyingKey();

        G1Point memory vk_x = ic[0];
        vk_x = addition(vk_x, scalar_mul(ic[1], input[0])); // minSalary
        vk_x = addition(vk_x, scalar_mul(ic[2], input[1])); // maxSalary
        vk_x = addition(vk_x, scalar_mul(ic[3], input[2])); // valid

        return pairing(
            negate(G1Point(a[0], a[1])),
            G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]),
            alpha1, beta2,
            vk_x, gamma2,
            G1Point(c[0], c[1]), delta2
        );
    }
}
